/* ============================================================
   MEMORIUM — Theme Family System Configuration
   Centralized data for 6 families × 4 themes = 24 themes.
   Colors are muted, material, paper-friendly (not saturated).
   Each theme controls the entire diary personality.
   ============================================================ */
(function () {
  'use strict';

  // All theme IDs — used for validation & enum
  const ALL_THEME_IDS = [
    'burgundy-journal',
    'rose-paper',
    'scarlet-vintage',
    'crimson-classic',
    'midnight-blue',
    'ocean-blue',
    'dusty-blue',
    'royal-blue',
    'forest-green',
    'sage-garden',
    'moss-vintage',
    'emerald-classic',
    'plum-velvet',
    'lavender-paper',
    'royal-purple',
    'dusty-violet',
    'classic-leather',
    'coffee-brown',
    'walnut',
    'sepia-vintage',
    'rose-blush',
    'dusty-pink',
    'blush',
    'vintage-pink',
  ];

  const DEFAULT_THEME = 'classic-leather';

  // Legacy 4-theme map for migration (+ alias for spec's "Rose" shorthand)
  const LEGACY_MAP = {
    parchment: 'classic-leather',
    vintage: 'sepia-vintage',
    aged: 'walnut',
    handwritten: 'blush',
    rose: 'rose-blush',
  };

  const FAMILIES = [
    { id: 'red', name: 'Red', swatch: '#6B2436', accent: '#8E3541' },
    { id: 'blue', name: 'Blue', swatch: '#1E3A5C', accent: '#4A6B8A' },
    { id: 'green', name: 'Green', swatch: '#2D4A3E', accent: '#6B8B74' },
    { id: 'purple', name: 'Purple', swatch: '#4A2E4A', accent: '#6B5A7A' },
    { id: 'brown', name: 'Brown', swatch: '#5C3D2E', accent: '#8B6A52' },
    { id: 'pink', name: 'Pink', swatch: '#8B5A6B', accent: '#C49AA6' },
  ];

  // Each theme: full material palette
  const THEMES = {
    // === RED FAMILY — warm, винтажный ===
    'burgundy-journal': {
      id: 'burgundy-journal',
      family: 'red',
      name: 'Burgundy Journal',
      colors: {
        cover: '#6B2436',
        coverEdge: '#4A1824',
        coverInner: '#7A2E3E',
        paper: '#F8F1E7',
        paperSecondary: '#EDE0CC',
        paperEdge: '#E5D8C4',
        text: '#3C2328',
        textMuted: '#7A5A5E',
        textLight: '#9B8E84',
        accent: '#8E3541',
        accentLight: '#B85C5C',
        border: '#D6C2B0',
        shadow: 'rgba(60,20,30,0.28)',
        ribbon: '#8E3541',
        bookmark: '#C9A227',
        buttonBg: '#6B2436',
        buttonText: '#F8F1E7',
      },
      paperTexture: 'burgundy',
      description: 'Deep wine leather with cream paper',
    },
    'rose-paper': {
      id: 'rose-paper',
      family: 'red',
      name: 'Rose Paper',
      colors: {
        cover: '#8B4A5E',
        coverEdge: '#6B3545',
        coverInner: '#9B5A6B',
        paper: '#FFF5F2',
        paperSecondary: '#F5E0D8',
        paperEdge: '#E8D0C8',
        text: '#4A2E35',
        textMuted: '#8B6B75',
        textLight: '#A68E95',
        accent: '#A64A5A',
        accentLight: '#C97A8A',
        border: '#DDC2B8',
        shadow: 'rgba(90,45,65,0.22)',
        ribbon: '#A64A5A',
        bookmark: '#D4A0A0',
        buttonBg: '#8B4A5E',
        buttonText: '#FFF5F2',
      },
      paperTexture: 'rose',
      description: 'Soft rose leather with blush paper',
    },
    'scarlet-vintage': {
      id: 'scarlet-vintage',
      family: 'red',
      name: 'Scarlet Vintage',
      colors: {
        cover: '#7A2E2E',
        coverEdge: '#5A1E1E',
        coverInner: '#8B3A3A',
        paper: '#FDF6EE',
        paperSecondary: '#F0E0CC',
        paperEdge: '#E0D0B8',
        text: '#3B1E1E',
        textMuted: '#7A4A4A',
        textLight: '#9B8A7A',
        accent: '#A63A2A',
        accentLight: '#C96A4A',
        border: '#D6C0A0',
        shadow: 'rgba(70,20,20,0.26)',
        ribbon: '#A63A2A',
        bookmark: '#C9A227',
        buttonBg: '#7A2E2E',
        buttonText: '#FDF6EE',
      },
      paperTexture: 'scarlet',
      description: 'Vintage scarlet with aged cream',
    },
    'crimson-classic': {
      id: 'crimson-classic',
      family: 'red',
      name: 'Crimson Classic',
      colors: {
        cover: '#8E3541',
        coverEdge: '#6B2430',
        coverInner: '#A0404E',
        paper: '#FFF8F0',
        paperSecondary: '#F5E8D8',
        paperEdge: '#EAD8C0',
        text: '#4A2328',
        textMuted: '#7A5A60',
        textLight: '#9B8E90',
        accent: '#8E3541',
        accentLight: '#B85A6A',
        border: '#D8C0B0',
        shadow: 'rgba(80,25,35,0.24)',
        ribbon: '#8E3541',
        bookmark: '#C9A227',
        buttonBg: '#8E3541',
        buttonText: '#FFF8F0',
      },
      paperTexture: 'crimson',
      description: 'Classic crimson with warm ivory',
    },

    // === BLUE FAMILY — cool, contemplative ===
    'midnight-blue': {
      id: 'midnight-blue',
      family: 'blue',
      name: 'Midnight Blue',
      colors: {
        cover: '#1E3A5C',
        coverEdge: '#152A42',
        coverInner: '#2A4A6B',
        paper: '#F0F2F5',
        paperSecondary: '#E0E4EA',
        paperEdge: '#D0D6E0',
        text: '#1E2A3A',
        textMuted: '#5A6B7A',
        textLight: '#8A9AAA',
        accent: '#2E5A7B',
        accentLight: '#4A7AA0',
        border: '#C0CAD8',
        shadow: 'rgba(20,35,55,0.28)',
        ribbon: '#2E5A7B',
        bookmark: '#C9A227',
        buttonBg: '#1E3A5C',
        buttonText: '#F0F2F5',
      },
      paperTexture: 'midnight',
      description: 'Deep midnight leather with cool paper',
    },
    'ocean-blue': {
      id: 'ocean-blue',
      family: 'blue',
      name: 'Ocean Blue',
      colors: {
        cover: '#2E5A7B',
        coverEdge: '#1E3E5A',
        coverInner: '#3A6A8B',
        paper: '#F5F8FA',
        paperSecondary: '#E8EEF2',
        paperEdge: '#D8E2EA',
        text: '#243342',
        textMuted: '#5A6E7E',
        textLight: '#8AA0B0',
        accent: '#3A7A9B',
        accentLight: '#5A9AC0',
        border: '#C8D6E0',
        shadow: 'rgba(30,50,80,0.22)',
        ribbon: '#3A7A9B',
        bookmark: '#7AC0C0',
        buttonBg: '#2E5A7B',
        buttonText: '#F5F8FA',
      },
      paperTexture: 'ocean',
      description: 'Ocean leather with sea-mist paper',
    },
    'dusty-blue': {
      id: 'dusty-blue',
      family: 'blue',
      name: 'Dusty Blue',
      colors: {
        cover: '#4A6B8A',
        coverEdge: '#3A556B',
        coverInner: '#5A7A9A',
        paper: '#F8F9FA',
        paperSecondary: '#EDEEF0',
        paperEdge: '#E0E2E5',
        text: '#2E3A4A',
        textMuted: '#6B7A8A',
        textLight: '#9AA8B5',
        accent: '#4A6B8A',
        accentLight: '#6B8AA8',
        border: '#D0D4DA',
        shadow: 'rgba(50,65,85,0.20)',
        ribbon: '#4A6B8A',
        bookmark: '#A8C0D0',
        buttonBg: '#4A6B8A',
        buttonText: '#F8F9FA',
      },
      paperTexture: 'dusty-blue',
      description: 'Muted dusty blue with soft grey paper',
    },
    'royal-blue': {
      id: 'royal-blue',
      family: 'blue',
      name: 'Royal Blue',
      colors: {
        cover: '#243B5A',
        coverEdge: '#1A2E4A',
        coverInner: '#2E4A6B',
        paper: '#F2F4F7',
        paperSecondary: '#E2E6EA',
        paperEdge: '#D2D8E0',
        text: '#1E2E42',
        textMuted: '#5A6E82',
        textLight: '#8A9AB0',
        accent: '#3A5A8A',
        accentLight: '#5A7AB0',
        border: '#C2CAD6',
        shadow: 'rgba(25,40,65,0.26)',
        ribbon: '#3A5A8A',
        bookmark: '#C9A227',
        buttonBg: '#243B5A',
        buttonText: '#F2F4F7',
      },
      paperTexture: 'royal',
      description: 'Royal navy with crisp paper',
    },

    // === GREEN FAMILY — natural, grounded ===
    'forest-green': {
      id: 'forest-green',
      family: 'green',
      name: 'Forest Green',
      colors: {
        cover: '#2D4A3E',
        coverEdge: '#1E332A',
        coverInner: '#3A5A4A',
        paper: '#F5F2EB',
        paperSecondary: '#E8E4D8',
        paperEdge: '#DDD8C8',
        text: '#2A3328',
        textMuted: '#6B7A6B',
        textLight: '#9AAA9A',
        accent: '#4A6B4A',
        accentLight: '#6B8B6B',
        border: '#C8C4B0',
        shadow: 'rgba(30,45,35,0.26)',
        ribbon: '#4A6B4A',
        bookmark: '#C9A227',
        buttonBg: '#2D4A3E',
        buttonText: '#F5F2EB',
      },
      paperTexture: 'forest',
      description: 'Deep forest with natural linen paper',
    },
    'sage-garden': {
      id: 'sage-garden',
      family: 'green',
      name: 'Sage Garden',
      colors: {
        cover: '#6B7F6B',
        coverEdge: '#5A6B5A',
        coverInner: '#7A8F7A',
        paper: '#FAF8F2',
        paperSecondary: '#F0EDE4',
        paperEdge: '#E8E4D8',
        text: '#3A4A3A',
        textMuted: '#6B7A6B',
        textLight: '#9AAA9A',
        accent: '#6D8B74',
        accentLight: '#8EAC95',
        border: '#D0CEC0',
        shadow: 'rgba(60,75,60,0.18)',
        ribbon: '#6D8B74',
        bookmark: '#C4D6C0',
        buttonBg: '#6B7F6B',
        buttonText: '#FAF8F2',
      },
      paperTexture: 'sage',
      description: 'Soft sage with garden paper',
    },
    'moss-vintage': {
      id: 'moss-vintage',
      family: 'green',
      name: 'Moss Vintage',
      colors: {
        cover: '#3E4A35',
        coverEdge: '#2E3525',
        coverInner: '#4A5A40',
        paper: '#F2EEE6',
        paperSecondary: '#E6E0D0',
        paperEdge: '#DAD0B8',
        text: '#2E3328',
        textMuted: '#6B6E5A',
        textLight: '#9A9A8A',
        accent: '#5A6B3A',
        accentLight: '#7A8B5A',
        border: '#C8C0A8',
        shadow: 'rgba(35,45,30,0.26)',
        ribbon: '#5A6B3A',
        bookmark: '#A8B58A',
        buttonBg: '#3E4A35',
        buttonText: '#F2EEE6',
      },
      paperTexture: 'moss',
      description: 'Vintage moss with aged paper',
    },
    'emerald-classic': {
      id: 'emerald-classic',
      family: 'green',
      name: 'Emerald Classic',
      colors: {
        cover: '#2F5D4A',
        coverEdge: '#1E3D32',
        coverInner: '#3A6B5A',
        paper: '#F8F6F0',
        paperSecondary: '#EDE8DC',
        paperEdge: '#E0DCC8',
        text: '#2A3A2E',
        textMuted: '#5A6E62',
        textLight: '#8A9A8E',
        accent: '#3A7A5A',
        accentLight: '#5A9A7A',
        border: '#C8D0C0',
        shadow: 'rgba(30,55,45,0.24)',
        ribbon: '#3A7A5A',
        bookmark: '#7AC49A',
        buttonBg: '#2F5D4A',
        buttonText: '#F8F6F0',
      },
      paperTexture: 'emerald',
      description: 'Emerald leather with ivory paper',
    },

    // === PURPLE FAMILY — elegant, regal ===
    'plum-velvet': {
      id: 'plum-velvet',
      family: 'purple',
      name: 'Plum Velvet',
      colors: {
        cover: '#4A2E4A',
        coverEdge: '#352035',
        coverInner: '#5A3A5A',
        paper: '#FAF5F8',
        paperSecondary: '#F0E8EE',
        paperEdge: '#E8DCE6',
        text: '#3A2A3A',
        textMuted: '#7A6B7A',
        textLight: '#9A8E9A',
        accent: '#6B4A6B',
        accentLight: '#8B6A8B',
        border: '#D8C8D8',
        shadow: 'rgba(55,35,55,0.26)',
        ribbon: '#6B4A6B',
        bookmark: '#C9A2C9',
        buttonBg: '#4A2E4A',
        buttonText: '#FAF5F8',
      },
      paperTexture: 'plum',
      description: 'Deep plum velvet with soft lilac paper',
    },
    'lavender-paper': {
      id: 'lavender-paper',
      family: 'purple',
      name: 'Lavender Paper',
      colors: {
        cover: '#6B5A7A',
        coverEdge: '#5A4A6B',
        coverInner: '#7A6B8A',
        paper: '#F8F5FA',
        paperSecondary: '#F0EAF2',
        paperEdge: '#E8E0EA',
        text: '#3A2E4A',
        textMuted: '#6B5A7A',
        textLight: '#9A8AAA',
        accent: '#7A5A9A',
        accentLight: '#9A7AC0',
        border: '#D6C8E0',
        shadow: 'rgba(65,50,85,0.20)',
        ribbon: '#7A5A9A',
        bookmark: '#C0A8D8',
        buttonBg: '#6B5A7A',
        buttonText: '#F8F5FA',
      },
      paperTexture: 'lavender',
      description: 'Gentle lavender with mist paper',
    },
    'royal-purple': {
      id: 'royal-purple',
      family: 'purple',
      name: 'Royal Purple',
      colors: {
        cover: '#3E2E5A',
        coverEdge: '#2A1E3E',
        coverInner: '#4A3A6B',
        paper: '#F5F2F8',
        paperSecondary: '#E8E2EE',
        paperEdge: '#DDD6E8',
        text: '#2E2442',
        textMuted: '#5A4E6E',
        textLight: '#8A7EA0',
        accent: '#5A3A7A',
        accentLight: '#7A5AAA',
        border: '#C8B8D8',
        shadow: 'rgba(40,30,65,0.28)',
        ribbon: '#5A3A7A',
        bookmark: '#C9A227',
        buttonBg: '#3E2E5A',
        buttonText: '#F5F2F8',
      },
      paperTexture: 'royal-purple',
      description: 'Royal purple with cool paper',
    },
    'dusty-violet': {
      id: 'dusty-violet',
      family: 'purple',
      name: 'Dusty Violet',
      colors: {
        cover: '#5A4A6B',
        coverEdge: '#4A3A5A',
        coverInner: '#6B5A7A',
        paper: '#FAF6F8',
        paperSecondary: '#F2E8F0',
        paperEdge: '#E8DCE8',
        text: '#3A2E3A',
        textMuted: '#6B5A6B',
        textLight: '#9A8A9A',
        accent: '#7A4A6B',
        accentLight: '#9A6A8A',
        border: '#D8C8D0',
        shadow: 'rgba(60,45,65,0.22)',
        ribbon: '#7A4A6B',
        bookmark: '#D4A0B8',
        buttonBg: '#5A4A6B',
        buttonText: '#FAF6F8',
      },
      paperTexture: 'violet',
      description: 'Dusty violet with warm blush paper',
    },

    // === BROWN FAMILY — classic leather, default ===
    'classic-leather': {
      id: 'classic-leather',
      family: 'brown',
      name: 'Classic Leather',
      colors: {
        cover: '#5C3D2E',
        coverEdge: '#4A2E20',
        coverInner: '#6B4F3B',
        paper: '#F8F1E7',
        paperSecondary: '#EFE3D0',
        paperEdge: '#E5D8C4',
        text: '#2F241F',
        textMuted: '#6E6259',
        textLight: '#9B8E84',
        accent: '#C9A227',
        accentLight: '#E0C350',
        border: '#DDD1BF',
        shadow: 'rgba(50,35,25,0.28)',
        ribbon: '#8B6A52',
        bookmark: '#C9A227',
        buttonBg: '#5C3D2E',
        buttonText: '#F8F1E7',
      },
      paperTexture: 'classic',
      description: 'Warm leather with vintage parchment',
    },
    'coffee-brown': {
      id: 'coffee-brown',
      family: 'brown',
      name: 'Coffee Brown',
      colors: {
        cover: '#4A3428',
        coverEdge: '#35251C',
        coverInner: '#5A3F2E',
        paper: '#FFF8F0',
        paperSecondary: '#F5EDE0',
        paperEdge: '#EDE0CC',
        text: '#2F241F',
        textMuted: '#6E6259',
        textLight: '#9B8E84',
        accent: '#A67B5B',
        accentLight: '#C4A882',
        border: '#DDD1BF',
        shadow: 'rgba(45,30,20,0.28)',
        ribbon: '#A67B5B',
        bookmark: '#C9A227',
        buttonBg: '#4A3428',
        buttonText: '#FFF8F0',
      },
      paperTexture: 'coffee',
      description: 'Rich coffee with cream paper',
    },
    walnut: {
      id: 'walnut',
      family: 'brown',
      name: 'Walnut',
      colors: {
        cover: '#6B4A35',
        coverEdge: '#5A3A28',
        coverInner: '#7A5A42',
        paper: '#FDF6EE',
        paperSecondary: '#F0E6D0',
        paperEdge: '#E8DCC0',
        text: '#3B2C23',
        textMuted: '#6E5A4A',
        textLight: '#9B8E7A',
        accent: '#8B6A52',
        accentLight: '#A68B6A',
        border: '#D6C2A8',
        shadow: 'rgba(65,40,25,0.24)',
        ribbon: '#8B6A52',
        bookmark: '#C9A227',
        buttonBg: '#6B4A35',
        buttonText: '#FDF6EE',
      },
      paperTexture: 'walnut',
      description: 'Walnut wood with honey paper',
    },
    'sepia-vintage': {
      id: 'sepia-vintage',
      family: 'brown',
      name: 'Sepia Vintage',
      colors: {
        cover: '#7A5A3E',
        coverEdge: '#6B4A30',
        coverInner: '#8B6B4E',
        paper: '#EFE3D0',
        paperSecondary: '#E5D8C4',
        paperEdge: '#DDD0B8',
        text: '#3B2C23',
        textMuted: '#6E5E4A',
        textLight: '#9B8E7A',
        accent: '#A67B5B',
        accentLight: '#C4A882',
        border: '#D0C0A8',
        shadow: 'rgba(70,50,35,0.22)',
        ribbon: '#A67B5B',
        bookmark: '#C9A227',
        buttonBg: '#7A5A3E',
        buttonText: '#EFE3D0',
      },
      paperTexture: 'sepia',
      description: 'Sepia leather with aged vintage paper',
    },

    // === PINK FAMILY — soft, romantic ===
    'rose-blush': {
      id: 'rose-blush',
      family: 'pink',
      name: 'Rose',
      colors: {
        cover: '#8B5A6B',
        coverEdge: '#6B4452',
        coverInner: '#9B6B7A',
        paper: '#FFF8F5',
        paperSecondary: '#FDEEE8',
        paperEdge: '#F5DDD6',
        text: '#4A2E3A',
        textMuted: '#7A5A6B',
        textLight: '#9B8A95',
        accent: '#A67B8A',
        accentLight: '#C49AA6',
        border: '#E0C8C0',
        shadow: 'rgba(85,55,70,0.20)',
        ribbon: '#A67B8A',
        bookmark: '#D4A0A0',
        buttonBg: '#8B5A6B',
        buttonText: '#FFF8F5',
      },
      paperTexture: 'rose-blush',
      description: 'Rose blush with warm cream paper',
    },
    'dusty-pink': {
      id: 'dusty-pink',
      family: 'pink',
      name: 'Dusty Pink',
      colors: {
        cover: '#A67B8A',
        coverEdge: '#8B6572',
        coverInner: '#B88A9A',
        paper: '#FFFAF8',
        paperSecondary: '#FFF0EC',
        paperEdge: '#F5E0DA',
        text: '#4A333E',
        textMuted: '#7A5A6A',
        textLight: '#9B8A95',
        accent: '#A67B8A',
        accentLight: '#C49AA6',
        border: '#E2C8C8',
        shadow: 'rgba(100,65,80,0.18)',
        ribbon: '#A67B8A',
        bookmark: '#C9A2B8',
        buttonBg: '#A67B8A',
        buttonText: '#FFFAF8',
      },
      paperTexture: 'dusty-pink',
      description: 'Dusty pink with soft ivory paper',
    },
    blush: {
      id: 'blush',
      family: 'pink',
      name: 'Blush',
      colors: {
        cover: '#C49AA6',
        coverEdge: '#A67B8A',
        coverInner: '#D4AAB8',
        paper: '#FFFAF1',
        paperSecondary: '#FFF2E8',
        paperEdge: '#F5E8DC',
        text: '#4A3428',
        textMuted: '#6E5A52',
        textLight: '#9B8E84',
        accent: '#C49AA6',
        accentLight: '#D4B0B8',
        border: '#E0D0C8',
        shadow: 'rgba(110,75,85,0.16)',
        ribbon: '#C49AA6',
        bookmark: '#C9A227',
        buttonBg: '#C49AA6',
        buttonText: '#4A3428',
      },
      paperTexture: 'blush',
      description: 'Pale blush with handwritten cream',
    },
    'vintage-pink': {
      id: 'vintage-pink',
      family: 'pink',
      name: 'Vintage Pink',
      colors: {
        cover: '#9B6B7A',
        coverEdge: '#7A5260',
        coverInner: '#AB7B8A',
        paper: '#FFF5F0',
        paperSecondary: '#F8E8E0',
        paperEdge: '#F0DDD4',
        text: '#4A2E3A',
        textMuted: '#7A5A68',
        textLight: '#9B8A90',
        accent: '#9B6B7A',
        accentLight: '#B88A9A',
        border: '#DDC8C0',
        shadow: 'rgba(90,60,75,0.20)',
        ribbon: '#9B6B7A',
        bookmark: '#C9A2A2',
        buttonBg: '#9B6B7A',
        buttonText: '#FFF5F0',
      },
      paperTexture: 'vintage-pink',
      description: 'Vintage pink with warm paper',
    },
  };

  // Helper APIs
  function isValidTheme(id) {
    return !!THEMES[id];
  }
  function getTheme(id) {
    return THEMES[id] || THEMES[DEFAULT_THEME];
  }
  function getFamilyThemes(familyId) {
    return Object.values(THEMES).filter(t => t.family === familyId);
  }
  function resolveThemeId(raw) {
    if (!raw) return DEFAULT_THEME;
    if (THEMES[raw]) return raw;
    if (LEGACY_MAP[raw]) return LEGACY_MAP[raw];
    return DEFAULT_THEME;
  }

  window.MemoriumThemeConfig = {
    FAMILIES,
    THEMES,
    ALL_THEME_IDS,
    DEFAULT_THEME,
    LEGACY_MAP,
    isValidTheme,
    getTheme,
    getFamilyThemes,
    resolveThemeId,
  };
})();
